---
abstract: 'translate find command lines to Perl code'
author:
  - 'Leon Timmermans <leont@cpan.org>'
build_requires:
  Devel::FindPerl: 0.009
  File::Path: 0
  File::Spec: 0
  File::Temp: 0
  IO::Handle: 0
  IPC::Open2: 0
  IPC::Open3: 0
  Perl::OSType: 0
  Test::More: 0
  constant: 0
  open: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.008, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-find2perl
provides:
  App::find2perl:
    file: script/find2perl
    version: 1.002
requires:
  File::Spec::Functions: 0
  strict: 0
  vars: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=App-find2perl
  repository: git://github.com/Leont/app-find2perl.git
version: 1.002
x_Dist_Zilla:
  perl:
    version: 5.018001
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Filter/GatherDir'
      version: 5.008
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/PruneCruft'
      version: 5.008
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Filter/ManifestSkip'
      version: 5.008
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/MetaYAML'
      version: 5.008
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/License'
      version: 5.008
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Filter/Readme'
      version: 5.008
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Filter/ShareDir'
      version: 5.008
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Filter/MakeMaker'
      version: 5.008
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/Manifest'
      version: 5.008
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Filter/TestRelease'
      version: 5.008
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Filter/ConfirmRelease'
      version: 5.008
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Filter/UploadToCPAN'
      version: 5.008
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: ExecDir
      version: 5.008
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder:
            - ExecDir
        Dist::Zilla::Role::MetaProvider::Provider:
          inherit_missing: 1
          inherit_version: 1
          meta_noindex: 1
      name: MetaProvides::Package
      version: 1.15000000
    -
      class: Dist::Zilla::Plugin::CheckChangesHasContent
      name: CheckChangesHasContent
      version: 0.006
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: MetaConfig
      version: 5.008
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: MetaJSON
      version: 5.008
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: 5.008
    -
      class: Dist::Zilla::Plugin::Repository
      name: Repository
      version: 0.19
    -
      class: Dist::Zilla::Plugin::Bugtracker
      name: Bugtracker
      version: 1.111080
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: Git::NextVersion
      version: 2.014
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: NextRelease
      version: 5.008
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Git/Check'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Git/Commit'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Git/Tag'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Git/Push'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: PkgVersion
      version: 5.008
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          filename: t/00-compile.t
          module_finder:
            - ':InstallModules'
          script_finder:
            - ':ExecFiles'
      name: Test::Compile
      version: 2.036
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 5.008
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 5.008
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 5.008
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 5.008
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 5.008
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 5.008
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: 5.008
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: 5.008
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 5.008
